<?php

namespace backend\models;

use common\models\Channel;
use Yii;

/**
 * This is the model class for table "finance_channel_bill_term".
 *
 * @property string $bill_id
 * @property string $invoice_id
 * @property string $period
 * @property integer $channel_id
 * @property string $time_zone
 * @property integer $start_time
 * @property integer $end_time
 * @property integer $clicks
 * @property integer $unique_clicks
 * @property integer $installs
 * @property integer $match_installs
 * @property integer $redirect_installs
 * @property integer $redirect_match_installs
 * @property string $pay_out
 * @property string $adv_price
 * @property string $daily_cap
 * @property string $cap
 * @property string $cost
 * @property string $redirect_cost
 * @property string $revenue
 * @property string $redirect_revenue
 * @property string $deduction
 * @property string $compensation
 * @property string $add_cost
 * @property string $final_cost
 * @property string $actual_margin
 * @property string $paid_amount
 * @property string $payable
 * @property string $apply_prepayment
 * @property string $balance
 * @property integer $status
 * @property integer $update_time
 * @property integer $create_time
 *
 * @property Channel $channel
 */
class FinanceChannelBillTerm extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'finance_channel_bill_term';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['bill_id', 'invoice_id', 'period', 'channel_id', 'start_time', 'end_time'], 'required'],
            [['channel_id', 'start_time', 'end_time', 'clicks', 'unique_clicks', 'installs', 'match_installs', 'redirect_installs', 'redirect_match_installs', 'status', 'update_time', 'create_time'], 'integer'],
            [['pay_out', 'adv_price', 'cost', 'redirect_cost', 'revenue', 'redirect_revenue', 'deduction', 'compensation', 'add_cost', 'final_cost', 'actual_margin', 'paid_amount', 'payable', 'apply_prepayment', 'balance'], 'number'],
            [['bill_id', 'period'], 'string', 'max' => 255],
            [['invoice_id', 'time_zone', 'daily_cap', 'cap'], 'string', 'max' => 100],
            [['channel_id'], 'exist', 'skipOnError' => true, 'targetClass' => Channel::className(), 'targetAttribute' => ['channel_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'bill_id' => 'Bill ID',
            'invoice_id' => 'Invoice ID',
            'period' => 'Period',
            'channel_id' => 'Channel ID',
            'time_zone' => 'Time Zone',
            'start_time' => 'Start Time',
            'end_time' => 'End Time',
            'clicks' => 'Clicks',
            'unique_clicks' => 'Unique Clicks',
            'installs' => 'Installs',
            'match_installs' => 'Match Installs',
            'redirect_installs' => 'Redirect Installs',
            'redirect_match_installs' => 'Redirect Match Installs',
            'pay_out' => 'Pay Out',
            'adv_price' => 'Adv Price',
            'daily_cap' => 'Daily Cap',
            'cap' => 'Cap',
            'cost' => 'Cost',
            'redirect_cost' => 'Redirect Cost',
            'revenue' => 'Revenue',
            'redirect_revenue' => 'Redirect Revenue',
            'deduction' => 'Deduction',
            'compensation' => 'Compensation',
            'add_cost' => 'Add Cost',
            'final_cost' => 'Final Cost',
            'actual_margin' => 'Actual Margin',
            'paid_amount' => 'Paid Amount',
            'payable' => 'Payable',
            'apply_prepayment' => 'Apply Prepayment',
            'balance' => 'Balance',
            'status' => 'Status',
            'update_time' => 'Update Time',
            'create_time' => 'Create Time',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getChannel()
    {
        return $this->hasOne(Channel::className(), ['id' => 'channel_id']);
    }

    public function beforeSave($insert)
    {
        if ($insert) {
            $this->create_time = time();
        } else {
            $this->update_time = time();
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
