<?php

namespace backend\models;

use common\models\Campaign;
use common\models\Channel;
use Yii;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "finance_channel_campaign_bill_term".
 *
 * @property string $bill_id
 * @property integer $channel_id
 * @property string $time_zone
 * @property integer $campaign_id
 * @property integer $start_time
 * @property integer $end_time
 * @property integer $clicks
 * @property integer $unique_clicks
 * @property integer $installs
 * @property integer $match_installs
 * @property integer $redirect_installs
 * @property integer $redirect_match_installs
 * @property string $pay_out
 * @property string $adv_price
 * @property string $daily_cap
 * @property string $cap
 * @property string $cost
 * @property string $redirect_cost
 * @property string $revenue
 * @property string $redirect_revenue
 * @property string $note
 * @property integer $create_time
 * @property integer $update_time
 *
 * @property Campaign $campaign
 * @property FinanceChannelBillTerm $bill
 * @property Channel $channel
 */
class FinanceChannelCampaignBillTerm extends ActiveRecord
{
    public $deduction_cost;
    public $deduction_revenue;
    public $pending_cost;
    public $pending_revenue;
    public $pending_id;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'finance_channel_campaign_bill_term';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['bill_id', 'channel_id', 'campaign_id', 'start_time', 'end_time'], 'required'],
            [['channel_id', 'campaign_id', 'start_time', 'end_time', 'clicks', 'unique_clicks', 'installs', 'match_installs', 'redirect_installs', 'redirect_match_installs', 'create_time', 'update_time'], 'integer'],
            [['pay_out', 'adv_price', 'cost', 'redirect_cost', 'revenue', 'redirect_revenue'], 'number'],
            [['note'], 'string'],
            [['deduction_cost','deduction_revenue','pending_cost','pending_revenue'],'safe'],
            [['bill_id'], 'string', 'max' => 255],
            [['time_zone', 'daily_cap', 'cap'], 'string', 'max' => 100],
            [['campaign_id'], 'exist', 'skipOnError' => true, 'targetClass' => Campaign::className(), 'targetAttribute' => ['campaign_id' => 'id']],
            [['bill_id'], 'exist', 'skipOnError' => true, 'targetClass' => FinanceChannelBillTerm::className(), 'targetAttribute' => ['bill_id' => 'bill_id']],
            [['channel_id'], 'exist', 'skipOnError' => true, 'targetClass' => Channel::className(), 'targetAttribute' => ['channel_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'bill_id' => 'Bill ID',
            'channel_id' => 'Channel ID',
            'time_zone' => 'Time Zone',
            'campaign_id' => 'Campaign ID',
            'start_time' => 'Start Time',
            'end_time' => 'End Time',
            'clicks' => 'Clicks',
            'unique_clicks' => 'Unique Clicks',
            'installs' => 'Installs',
            'match_installs' => 'Match Installs',
            'redirect_installs' => 'Redirect Installs',
            'redirect_match_installs' => 'Redirect Match Installs',
            'pay_out' => 'Pay Out',
            'adv_price' => 'Adv Price',
            'daily_cap' => 'Daily Cap',
            'cap' => 'Cap',
            'cost' => 'Cost',
            'redirect_cost' => 'Redirect Cost',
            'revenue' => 'Revenue',
            'redirect_revenue' => 'Redirect Revenue',
            'note' => 'Note',
            'create_time' => 'Create Time',
            'update_time' => 'Update Time',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCampaign()
    {
        return $this->hasOne(Campaign::className(), ['id' => 'campaign_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBill()
    {
        return $this->hasOne(FinanceChannelBillTerm::className(), ['bill_id' => 'bill_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getChannel()
    {
        return $this->hasOne(Channel::className(), ['id' => 'channel_id']);
    }

    public function beforeSave($insert)
    {
        if ($insert) {
            $this->create_time = time();
        } else {
            $this->update_time = time();
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public static function statsByAdv($start_time, $end_time, $channel_id)
    {
        $query = static::find();
        $query->select([
            'sum(clicks) clicks',
            'sum(unique_clicks) unique_clicks',
            'sum(installs) installs',
            'sum(match_installs) match_installs',
            'sum(redirect_installs) redirect_installs',
            'sum(redirect_match_installs) redirect_match_installs',
            'sum(pay_out) pay_out',
            'sum(adv_price) adv_price',
            'sum(cost) cost',
            'sum(redirect_cost) redirect_cost',
            'sum(revenue) revenue',
            'sum(redirect_revenue) redirect_revenue',
        ]);
        $query->where(['start_time' => $start_time]);
        $query->andWhere(['end_time' => $end_time]);
        $query->andWhere(['channel_id' => $channel_id]);
        return $query->one();
    }

}
