<?php
namespace console\controllers;

use common\models\Feed;
use linslin\yii2\curl\Curl;
use yii\console\Controller;

/**
 * Created by PhpStorm.
 * User: wh wu
 * Date: 1/15/2017
 * Time: 3:39 PM
 */
class AuditController extends Controller
{

    public function actionIndex()
    {
        echo "sdfadsf \n";
    }

    public function actionCount_feed()
    {
        return parent::actions(); // TODO: Change the autogenerated stub
    }

    public function actionPost_back()
    {
        $this->layout = false;
        $curl = new Curl();
        $feeds = Feed::findAll(['is_count'=>0]);

//        $response = $curl->get('http://superads.cn/index.php/stream/feed?click_id=0000000');
//        $response = $curl->reset()
//            ->setOption(
//                CURLOPT_POSTFIELDS,
//                http_build_query(array(
//                        'click_id' => '000value',
//                        '_csrf'=>'ZEZ6Y0xrY3ARGS42fTwhMQgkDgF6BCEGEx4SMXQMBR4CPy0iPCIwNQ==',
//                    )
//                ))
//            ->post('superads.cn/index.php/stream/feed');
//        var_dump($response);

        echo "pppppppppppp \n";
    }
}