<?php
namespace console\controllers;
use yii\console\Controller;

/**
 * Created by PhpStorm.
 * User: wh wu
 * Date: 1/15/2017
 * Time: 3:39 PM
 */
class AuditController extends Controller
{

    public function actionIndex()
    {
        echo "sdfadsf \n";
    }

    public function actionCount_feed()
    {
        return parent::actions(); // TODO: Change the autogenerated stub
    }

    public function actionPost_back()
    {
        return parent::actions(); // TODO: Change the autogenerated stub
    }
}