<?php

namespace frontend\models;

use api\modules\v1\models\Channel;
use Yii;
use yii\base\Model;

class ProfileForm extends Model
{
    public      $company;
    public      $firstname;
    public      $lastname;
    public      $phone1;
    public      $skype;
    public      $email;
    public      $company_address;
    /**
     * @var Channel
     */
    private $channel;

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['company', 'firstname', 'lastname','phone1','skype','email','company_address'], 'safe'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [

            'company' => 'Company',
            'firstname' => 'First Name',
            'lastname' => 'Last Name',
            'phone1' => 'Phone',
            'skype' => 'Skype',
            'email' => 'Email',
            'company_address' => 'Company Address',
        ];
    }

    public function update()
    {
        if ($this->validate()) {
            $this->channel = Channel::findIdentity(Yii::$app->user->getId());
            $this->channel->company = $this->company;
            $this->channel->firstname = $this->firstname;
            $this->channel->lastname = $this->lastname;
            $this->channel->phone1 = $this->phone1;
            $this->channel->skype = $this->skype;
            $this->channel->email = $this->email;
            $this->channel->company_address = $this->company_address;
            if ($this->channel->save()) {
                return true;
            }
        }
        return null;
    }

//    public function beforeValidate()
//    {
//        if (is_array($this->payment_way)) {
//            $this->payment_way = implode(',', $this->payment_way);
//        }
//        return parent::beforeValidate(); // TODO: Change the autogenerated stub
//    }

}
